export const GET_DATA = 'GET_DATA';
export const GET_DATA_ATTEMPT = 'GET_DATA_ATTEMPT';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAIL = 'GET_DATA_FAIL';

export const SUBMIT_DATA = 'SUBMIT_DATA';
export const SUBMIT_DATA_ATTEMPT = 'SUBMIT_DATA_ATTEMPT';
export const SUBMIT_DATA_SUCCESS = 'SUBMIT_DATA_SUCCESS';
export const SUBMIT_DATA_FAIL = 'SUBMIT_DATA_FAIL';

export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const RESET_STATE = 'RESET_STATE';
