export const GET_DATA = 'GET_DATA';
export const GET_DATA_ATTEMPT = 'GET_DATA_ATTEMPT';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAIL = 'GET_DATA_FAIL';

export const SUBMIT_DATA = 'SUBMIT_DATA';
export const SUBMIT_DATA_ATTEMPT = 'SUBMIT_DATA_ATTEMPT';
export const SUBMIT_DATA_SUCCESS = 'SUBMIT_DATA_SUCCESS';
export const SUBMIT_DATA_FAIL = 'SUBMIT_DATA_FAIL';

export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const RESET_STATE = 'RESET_STATE';

export const CHANGE_WIDTH='CHANGE_WIDTH';
export const RESET_WIDTH='RESET_WIDTH';

export const CHANGE_STUDENT_NAME='CHANGE_STUDENT_NAME';
export const CHANGE_STUDENT_FATHER_NAME='CHANGE_STUDENT_FATHER_NAME';
export const CHANGE_STUDENT_AGE='CHANGE_STUDENT_AGE';
export const CHANGE_STUDENT_ADRESS='CHANGE_STUDENT_ADRESS';


export const SUBMIT_STUDENT_DATA = 'SUBMIT_STUDENT_DATA';
export const SUBMIT_STUDENT_DATA_ATTEMPT = 'SUBMIT_STUDENT_DATA_ATTEMPT';
export const SUBMIT_STUDENT_DATA_SUCCESS = 'SUBMIT_STUDENT_DATA_SUCCESS';
export const SUBMIT_STUDENT_DATA_FAIL = 'SUBMIT_STUDENT_DATA_FAIL';
export const RESET_STUDENT_STATE='RESET_STUDENT_STATE';
